/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ru.nkz.ivcgzo.thriftCommon.classifier;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ClassifierSortOrder implements org.apache.thrift.TEnum {
  none(0),
  ascending(1),
  descending(2);

  private final int value;

  private ClassifierSortOrder(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ClassifierSortOrder findByValue(int value) { 
    switch (value) {
      case 0:
        return none;
      case 1:
        return ascending;
      case 2:
        return descending;
      default:
        return null;
    }
  }
}
