/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ru.nkz.ivcgzo.thriftRegPatient;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class PatientAgent implements org.apache.thrift.TBase<PatientAgent, PatientAgent._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PatientAgent");

  private static final org.apache.thrift.protocol.TField NPASP_FIELD_DESC = new org.apache.thrift.protocol.TField("npasp", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField FAM_FIELD_DESC = new org.apache.thrift.protocol.TField("fam", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField IM_FIELD_DESC = new org.apache.thrift.protocol.TField("im", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField OT_FIELD_DESC = new org.apache.thrift.protocol.TField("ot", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField DATAR_FIELD_DESC = new org.apache.thrift.protocol.TField("datar", org.apache.thrift.protocol.TType.I64, (short)5);
  private static final org.apache.thrift.protocol.TField POL_FIELD_DESC = new org.apache.thrift.protocol.TField("pol", org.apache.thrift.protocol.TType.I32, (short)6);
  private static final org.apache.thrift.protocol.TField NAME_STR_FIELD_DESC = new org.apache.thrift.protocol.TField("name_str", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField OGRN_STR_FIELD_DESC = new org.apache.thrift.protocol.TField("ogrn_str", org.apache.thrift.protocol.TType.STRING, (short)8);
  private static final org.apache.thrift.protocol.TField VPOLIS_FIELD_DESC = new org.apache.thrift.protocol.TField("vpolis", org.apache.thrift.protocol.TType.I32, (short)9);
  private static final org.apache.thrift.protocol.TField SPOLIS_FIELD_DESC = new org.apache.thrift.protocol.TField("spolis", org.apache.thrift.protocol.TType.STRING, (short)10);
  private static final org.apache.thrift.protocol.TField NPOLIS_FIELD_DESC = new org.apache.thrift.protocol.TField("npolis", org.apache.thrift.protocol.TType.STRING, (short)11);
  private static final org.apache.thrift.protocol.TField TDOC_FIELD_DESC = new org.apache.thrift.protocol.TField("tdoc", org.apache.thrift.protocol.TType.I32, (short)12);
  private static final org.apache.thrift.protocol.TField DOCSER_FIELD_DESC = new org.apache.thrift.protocol.TField("docser", org.apache.thrift.protocol.TType.STRING, (short)13);
  private static final org.apache.thrift.protocol.TField DOCNUM_FIELD_DESC = new org.apache.thrift.protocol.TField("docnum", org.apache.thrift.protocol.TType.STRING, (short)14);
  private static final org.apache.thrift.protocol.TField BIRTHPLACE_FIELD_DESC = new org.apache.thrift.protocol.TField("birthplace", org.apache.thrift.protocol.TType.STRING, (short)15);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PatientAgentStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PatientAgentTupleSchemeFactory());
  }

  public int npasp; // required
  public String fam; // required
  public String im; // required
  public String ot; // required
  public long datar; // required
  public int pol; // required
  public String name_str; // required
  public String ogrn_str; // required
  public int vpolis; // required
  public String spolis; // required
  public String npolis; // required
  public int tdoc; // required
  public String docser; // required
  public String docnum; // required
  public String birthplace; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NPASP((short)1, "npasp"),
    FAM((short)2, "fam"),
    IM((short)3, "im"),
    OT((short)4, "ot"),
    DATAR((short)5, "datar"),
    POL((short)6, "pol"),
    NAME_STR((short)7, "name_str"),
    OGRN_STR((short)8, "ogrn_str"),
    VPOLIS((short)9, "vpolis"),
    SPOLIS((short)10, "spolis"),
    NPOLIS((short)11, "npolis"),
    TDOC((short)12, "tdoc"),
    DOCSER((short)13, "docser"),
    DOCNUM((short)14, "docnum"),
    BIRTHPLACE((short)15, "birthplace");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NPASP
          return NPASP;
        case 2: // FAM
          return FAM;
        case 3: // IM
          return IM;
        case 4: // OT
          return OT;
        case 5: // DATAR
          return DATAR;
        case 6: // POL
          return POL;
        case 7: // NAME_STR
          return NAME_STR;
        case 8: // OGRN_STR
          return OGRN_STR;
        case 9: // VPOLIS
          return VPOLIS;
        case 10: // SPOLIS
          return SPOLIS;
        case 11: // NPOLIS
          return NPOLIS;
        case 12: // TDOC
          return TDOC;
        case 13: // DOCSER
          return DOCSER;
        case 14: // DOCNUM
          return DOCNUM;
        case 15: // BIRTHPLACE
          return BIRTHPLACE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __NPASP_ISSET_ID = 0;
  private static final int __DATAR_ISSET_ID = 1;
  private static final int __POL_ISSET_ID = 2;
  private static final int __VPOLIS_ISSET_ID = 3;
  private static final int __TDOC_ISSET_ID = 4;
  private BitSet __isset_bit_vector = new BitSet(5);
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NPASP, new org.apache.thrift.meta_data.FieldMetaData("npasp", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.FAM, new org.apache.thrift.meta_data.FieldMetaData("fam", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IM, new org.apache.thrift.meta_data.FieldMetaData("im", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OT, new org.apache.thrift.meta_data.FieldMetaData("ot", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DATAR, new org.apache.thrift.meta_data.FieldMetaData("datar", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.POL, new org.apache.thrift.meta_data.FieldMetaData("pol", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.NAME_STR, new org.apache.thrift.meta_data.FieldMetaData("name_str", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OGRN_STR, new org.apache.thrift.meta_data.FieldMetaData("ogrn_str", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VPOLIS, new org.apache.thrift.meta_data.FieldMetaData("vpolis", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SPOLIS, new org.apache.thrift.meta_data.FieldMetaData("spolis", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NPOLIS, new org.apache.thrift.meta_data.FieldMetaData("npolis", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TDOC, new org.apache.thrift.meta_data.FieldMetaData("tdoc", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.DOCSER, new org.apache.thrift.meta_data.FieldMetaData("docser", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DOCNUM, new org.apache.thrift.meta_data.FieldMetaData("docnum", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BIRTHPLACE, new org.apache.thrift.meta_data.FieldMetaData("birthplace", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PatientAgent.class, metaDataMap);
  }

  public PatientAgent() {
  }

  public PatientAgent(
    int npasp,
    String fam,
    String im,
    String ot,
    long datar,
    int pol,
    String name_str,
    String ogrn_str,
    int vpolis,
    String spolis,
    String npolis,
    int tdoc,
    String docser,
    String docnum,
    String birthplace)
  {
    this();
    this.npasp = npasp;
    setNpaspIsSet(true);
    this.fam = fam;
    this.im = im;
    this.ot = ot;
    this.datar = datar;
    setDatarIsSet(true);
    this.pol = pol;
    setPolIsSet(true);
    this.name_str = name_str;
    this.ogrn_str = ogrn_str;
    this.vpolis = vpolis;
    setVpolisIsSet(true);
    this.spolis = spolis;
    this.npolis = npolis;
    this.tdoc = tdoc;
    setTdocIsSet(true);
    this.docser = docser;
    this.docnum = docnum;
    this.birthplace = birthplace;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PatientAgent(PatientAgent other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    this.npasp = other.npasp;
    if (other.isSetFam()) {
      this.fam = other.fam;
    }
    if (other.isSetIm()) {
      this.im = other.im;
    }
    if (other.isSetOt()) {
      this.ot = other.ot;
    }
    this.datar = other.datar;
    this.pol = other.pol;
    if (other.isSetName_str()) {
      this.name_str = other.name_str;
    }
    if (other.isSetOgrn_str()) {
      this.ogrn_str = other.ogrn_str;
    }
    this.vpolis = other.vpolis;
    if (other.isSetSpolis()) {
      this.spolis = other.spolis;
    }
    if (other.isSetNpolis()) {
      this.npolis = other.npolis;
    }
    this.tdoc = other.tdoc;
    if (other.isSetDocser()) {
      this.docser = other.docser;
    }
    if (other.isSetDocnum()) {
      this.docnum = other.docnum;
    }
    if (other.isSetBirthplace()) {
      this.birthplace = other.birthplace;
    }
  }

  public PatientAgent deepCopy() {
    return new PatientAgent(this);
  }

  @Override
  public void clear() {
    setNpaspIsSet(false);
    this.npasp = 0;
    this.fam = null;
    this.im = null;
    this.ot = null;
    setDatarIsSet(false);
    this.datar = 0;
    setPolIsSet(false);
    this.pol = 0;
    this.name_str = null;
    this.ogrn_str = null;
    setVpolisIsSet(false);
    this.vpolis = 0;
    this.spolis = null;
    this.npolis = null;
    setTdocIsSet(false);
    this.tdoc = 0;
    this.docser = null;
    this.docnum = null;
    this.birthplace = null;
  }

  public int getNpasp() {
    return this.npasp;
  }

  public PatientAgent setNpasp(int npasp) {
    this.npasp = npasp;
    setNpaspIsSet(true);
    return this;
  }

  public void unsetNpasp() {
    __isset_bit_vector.clear(__NPASP_ISSET_ID);
  }

  /** Returns true if field npasp is set (has been assigned a value) and false otherwise */
  public boolean isSetNpasp() {
    return __isset_bit_vector.get(__NPASP_ISSET_ID);
  }

  public void setNpaspIsSet(boolean value) {
    __isset_bit_vector.set(__NPASP_ISSET_ID, value);
  }

  public String getFam() {
    return this.fam;
  }

  public PatientAgent setFam(String fam) {
    this.fam = fam;
    return this;
  }

  public void unsetFam() {
    this.fam = null;
  }

  /** Returns true if field fam is set (has been assigned a value) and false otherwise */
  public boolean isSetFam() {
    return this.fam != null;
  }

  public void setFamIsSet(boolean value) {
    if (!value) {
      this.fam = null;
    }
  }

  public String getIm() {
    return this.im;
  }

  public PatientAgent setIm(String im) {
    this.im = im;
    return this;
  }

  public void unsetIm() {
    this.im = null;
  }

  /** Returns true if field im is set (has been assigned a value) and false otherwise */
  public boolean isSetIm() {
    return this.im != null;
  }

  public void setImIsSet(boolean value) {
    if (!value) {
      this.im = null;
    }
  }

  public String getOt() {
    return this.ot;
  }

  public PatientAgent setOt(String ot) {
    this.ot = ot;
    return this;
  }

  public void unsetOt() {
    this.ot = null;
  }

  /** Returns true if field ot is set (has been assigned a value) and false otherwise */
  public boolean isSetOt() {
    return this.ot != null;
  }

  public void setOtIsSet(boolean value) {
    if (!value) {
      this.ot = null;
    }
  }

  public long getDatar() {
    return this.datar;
  }

  public PatientAgent setDatar(long datar) {
    this.datar = datar;
    setDatarIsSet(true);
    return this;
  }

  public void unsetDatar() {
    __isset_bit_vector.clear(__DATAR_ISSET_ID);
  }

  /** Returns true if field datar is set (has been assigned a value) and false otherwise */
  public boolean isSetDatar() {
    return __isset_bit_vector.get(__DATAR_ISSET_ID);
  }

  public void setDatarIsSet(boolean value) {
    __isset_bit_vector.set(__DATAR_ISSET_ID, value);
  }

  public int getPol() {
    return this.pol;
  }

  public PatientAgent setPol(int pol) {
    this.pol = pol;
    setPolIsSet(true);
    return this;
  }

  public void unsetPol() {
    __isset_bit_vector.clear(__POL_ISSET_ID);
  }

  /** Returns true if field pol is set (has been assigned a value) and false otherwise */
  public boolean isSetPol() {
    return __isset_bit_vector.get(__POL_ISSET_ID);
  }

  public void setPolIsSet(boolean value) {
    __isset_bit_vector.set(__POL_ISSET_ID, value);
  }

  public String getName_str() {
    return this.name_str;
  }

  public PatientAgent setName_str(String name_str) {
    this.name_str = name_str;
    return this;
  }

  public void unsetName_str() {
    this.name_str = null;
  }

  /** Returns true if field name_str is set (has been assigned a value) and false otherwise */
  public boolean isSetName_str() {
    return this.name_str != null;
  }

  public void setName_strIsSet(boolean value) {
    if (!value) {
      this.name_str = null;
    }
  }

  public String getOgrn_str() {
    return this.ogrn_str;
  }

  public PatientAgent setOgrn_str(String ogrn_str) {
    this.ogrn_str = ogrn_str;
    return this;
  }

  public void unsetOgrn_str() {
    this.ogrn_str = null;
  }

  /** Returns true if field ogrn_str is set (has been assigned a value) and false otherwise */
  public boolean isSetOgrn_str() {
    return this.ogrn_str != null;
  }

  public void setOgrn_strIsSet(boolean value) {
    if (!value) {
      this.ogrn_str = null;
    }
  }

  public int getVpolis() {
    return this.vpolis;
  }

  public PatientAgent setVpolis(int vpolis) {
    this.vpolis = vpolis;
    setVpolisIsSet(true);
    return this;
  }

  public void unsetVpolis() {
    __isset_bit_vector.clear(__VPOLIS_ISSET_ID);
  }

  /** Returns true if field vpolis is set (has been assigned a value) and false otherwise */
  public boolean isSetVpolis() {
    return __isset_bit_vector.get(__VPOLIS_ISSET_ID);
  }

  public void setVpolisIsSet(boolean value) {
    __isset_bit_vector.set(__VPOLIS_ISSET_ID, value);
  }

  public String getSpolis() {
    return this.spolis;
  }

  public PatientAgent setSpolis(String spolis) {
    this.spolis = spolis;
    return this;
  }

  public void unsetSpolis() {
    this.spolis = null;
  }

  /** Returns true if field spolis is set (has been assigned a value) and false otherwise */
  public boolean isSetSpolis() {
    return this.spolis != null;
  }

  public void setSpolisIsSet(boolean value) {
    if (!value) {
      this.spolis = null;
    }
  }

  public String getNpolis() {
    return this.npolis;
  }

  public PatientAgent setNpolis(String npolis) {
    this.npolis = npolis;
    return this;
  }

  public void unsetNpolis() {
    this.npolis = null;
  }

  /** Returns true if field npolis is set (has been assigned a value) and false otherwise */
  public boolean isSetNpolis() {
    return this.npolis != null;
  }

  public void setNpolisIsSet(boolean value) {
    if (!value) {
      this.npolis = null;
    }
  }

  public int getTdoc() {
    return this.tdoc;
  }

  public PatientAgent setTdoc(int tdoc) {
    this.tdoc = tdoc;
    setTdocIsSet(true);
    return this;
  }

  public void unsetTdoc() {
    __isset_bit_vector.clear(__TDOC_ISSET_ID);
  }

  /** Returns true if field tdoc is set (has been assigned a value) and false otherwise */
  public boolean isSetTdoc() {
    return __isset_bit_vector.get(__TDOC_ISSET_ID);
  }

  public void setTdocIsSet(boolean value) {
    __isset_bit_vector.set(__TDOC_ISSET_ID, value);
  }

  public String getDocser() {
    return this.docser;
  }

  public PatientAgent setDocser(String docser) {
    this.docser = docser;
    return this;
  }

  public void unsetDocser() {
    this.docser = null;
  }

  /** Returns true if field docser is set (has been assigned a value) and false otherwise */
  public boolean isSetDocser() {
    return this.docser != null;
  }

  public void setDocserIsSet(boolean value) {
    if (!value) {
      this.docser = null;
    }
  }

  public String getDocnum() {
    return this.docnum;
  }

  public PatientAgent setDocnum(String docnum) {
    this.docnum = docnum;
    return this;
  }

  public void unsetDocnum() {
    this.docnum = null;
  }

  /** Returns true if field docnum is set (has been assigned a value) and false otherwise */
  public boolean isSetDocnum() {
    return this.docnum != null;
  }

  public void setDocnumIsSet(boolean value) {
    if (!value) {
      this.docnum = null;
    }
  }

  public String getBirthplace() {
    return this.birthplace;
  }

  public PatientAgent setBirthplace(String birthplace) {
    this.birthplace = birthplace;
    return this;
  }

  public void unsetBirthplace() {
    this.birthplace = null;
  }

  /** Returns true if field birthplace is set (has been assigned a value) and false otherwise */
  public boolean isSetBirthplace() {
    return this.birthplace != null;
  }

  public void setBirthplaceIsSet(boolean value) {
    if (!value) {
      this.birthplace = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case NPASP:
      if (value == null) {
        unsetNpasp();
      } else {
        setNpasp((Integer)value);
      }
      break;

    case FAM:
      if (value == null) {
        unsetFam();
      } else {
        setFam((String)value);
      }
      break;

    case IM:
      if (value == null) {
        unsetIm();
      } else {
        setIm((String)value);
      }
      break;

    case OT:
      if (value == null) {
        unsetOt();
      } else {
        setOt((String)value);
      }
      break;

    case DATAR:
      if (value == null) {
        unsetDatar();
      } else {
        setDatar((Long)value);
      }
      break;

    case POL:
      if (value == null) {
        unsetPol();
      } else {
        setPol((Integer)value);
      }
      break;

    case NAME_STR:
      if (value == null) {
        unsetName_str();
      } else {
        setName_str((String)value);
      }
      break;

    case OGRN_STR:
      if (value == null) {
        unsetOgrn_str();
      } else {
        setOgrn_str((String)value);
      }
      break;

    case VPOLIS:
      if (value == null) {
        unsetVpolis();
      } else {
        setVpolis((Integer)value);
      }
      break;

    case SPOLIS:
      if (value == null) {
        unsetSpolis();
      } else {
        setSpolis((String)value);
      }
      break;

    case NPOLIS:
      if (value == null) {
        unsetNpolis();
      } else {
        setNpolis((String)value);
      }
      break;

    case TDOC:
      if (value == null) {
        unsetTdoc();
      } else {
        setTdoc((Integer)value);
      }
      break;

    case DOCSER:
      if (value == null) {
        unsetDocser();
      } else {
        setDocser((String)value);
      }
      break;

    case DOCNUM:
      if (value == null) {
        unsetDocnum();
      } else {
        setDocnum((String)value);
      }
      break;

    case BIRTHPLACE:
      if (value == null) {
        unsetBirthplace();
      } else {
        setBirthplace((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case NPASP:
      return Integer.valueOf(getNpasp());

    case FAM:
      return getFam();

    case IM:
      return getIm();

    case OT:
      return getOt();

    case DATAR:
      return Long.valueOf(getDatar());

    case POL:
      return Integer.valueOf(getPol());

    case NAME_STR:
      return getName_str();

    case OGRN_STR:
      return getOgrn_str();

    case VPOLIS:
      return Integer.valueOf(getVpolis());

    case SPOLIS:
      return getSpolis();

    case NPOLIS:
      return getNpolis();

    case TDOC:
      return Integer.valueOf(getTdoc());

    case DOCSER:
      return getDocser();

    case DOCNUM:
      return getDocnum();

    case BIRTHPLACE:
      return getBirthplace();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case NPASP:
      return isSetNpasp();
    case FAM:
      return isSetFam();
    case IM:
      return isSetIm();
    case OT:
      return isSetOt();
    case DATAR:
      return isSetDatar();
    case POL:
      return isSetPol();
    case NAME_STR:
      return isSetName_str();
    case OGRN_STR:
      return isSetOgrn_str();
    case VPOLIS:
      return isSetVpolis();
    case SPOLIS:
      return isSetSpolis();
    case NPOLIS:
      return isSetNpolis();
    case TDOC:
      return isSetTdoc();
    case DOCSER:
      return isSetDocser();
    case DOCNUM:
      return isSetDocnum();
    case BIRTHPLACE:
      return isSetBirthplace();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof PatientAgent)
      return this.equals((PatientAgent)that);
    return false;
  }

  public boolean equals(PatientAgent that) {
    if (that == null)
      return false;

    boolean this_present_npasp = true;
    boolean that_present_npasp = true;
    if (this_present_npasp || that_present_npasp) {
      if (!(this_present_npasp && that_present_npasp))
        return false;
      if (this.npasp != that.npasp)
        return false;
    }

    boolean this_present_fam = true && this.isSetFam();
    boolean that_present_fam = true && that.isSetFam();
    if (this_present_fam || that_present_fam) {
      if (!(this_present_fam && that_present_fam))
        return false;
      if (!this.fam.equals(that.fam))
        return false;
    }

    boolean this_present_im = true && this.isSetIm();
    boolean that_present_im = true && that.isSetIm();
    if (this_present_im || that_present_im) {
      if (!(this_present_im && that_present_im))
        return false;
      if (!this.im.equals(that.im))
        return false;
    }

    boolean this_present_ot = true && this.isSetOt();
    boolean that_present_ot = true && that.isSetOt();
    if (this_present_ot || that_present_ot) {
      if (!(this_present_ot && that_present_ot))
        return false;
      if (!this.ot.equals(that.ot))
        return false;
    }

    boolean this_present_datar = true;
    boolean that_present_datar = true;
    if (this_present_datar || that_present_datar) {
      if (!(this_present_datar && that_present_datar))
        return false;
      if (this.datar != that.datar)
        return false;
    }

    boolean this_present_pol = true;
    boolean that_present_pol = true;
    if (this_present_pol || that_present_pol) {
      if (!(this_present_pol && that_present_pol))
        return false;
      if (this.pol != that.pol)
        return false;
    }

    boolean this_present_name_str = true && this.isSetName_str();
    boolean that_present_name_str = true && that.isSetName_str();
    if (this_present_name_str || that_present_name_str) {
      if (!(this_present_name_str && that_present_name_str))
        return false;
      if (!this.name_str.equals(that.name_str))
        return false;
    }

    boolean this_present_ogrn_str = true && this.isSetOgrn_str();
    boolean that_present_ogrn_str = true && that.isSetOgrn_str();
    if (this_present_ogrn_str || that_present_ogrn_str) {
      if (!(this_present_ogrn_str && that_present_ogrn_str))
        return false;
      if (!this.ogrn_str.equals(that.ogrn_str))
        return false;
    }

    boolean this_present_vpolis = true;
    boolean that_present_vpolis = true;
    if (this_present_vpolis || that_present_vpolis) {
      if (!(this_present_vpolis && that_present_vpolis))
        return false;
      if (this.vpolis != that.vpolis)
        return false;
    }

    boolean this_present_spolis = true && this.isSetSpolis();
    boolean that_present_spolis = true && that.isSetSpolis();
    if (this_present_spolis || that_present_spolis) {
      if (!(this_present_spolis && that_present_spolis))
        return false;
      if (!this.spolis.equals(that.spolis))
        return false;
    }

    boolean this_present_npolis = true && this.isSetNpolis();
    boolean that_present_npolis = true && that.isSetNpolis();
    if (this_present_npolis || that_present_npolis) {
      if (!(this_present_npolis && that_present_npolis))
        return false;
      if (!this.npolis.equals(that.npolis))
        return false;
    }

    boolean this_present_tdoc = true;
    boolean that_present_tdoc = true;
    if (this_present_tdoc || that_present_tdoc) {
      if (!(this_present_tdoc && that_present_tdoc))
        return false;
      if (this.tdoc != that.tdoc)
        return false;
    }

    boolean this_present_docser = true && this.isSetDocser();
    boolean that_present_docser = true && that.isSetDocser();
    if (this_present_docser || that_present_docser) {
      if (!(this_present_docser && that_present_docser))
        return false;
      if (!this.docser.equals(that.docser))
        return false;
    }

    boolean this_present_docnum = true && this.isSetDocnum();
    boolean that_present_docnum = true && that.isSetDocnum();
    if (this_present_docnum || that_present_docnum) {
      if (!(this_present_docnum && that_present_docnum))
        return false;
      if (!this.docnum.equals(that.docnum))
        return false;
    }

    boolean this_present_birthplace = true && this.isSetBirthplace();
    boolean that_present_birthplace = true && that.isSetBirthplace();
    if (this_present_birthplace || that_present_birthplace) {
      if (!(this_present_birthplace && that_present_birthplace))
        return false;
      if (!this.birthplace.equals(that.birthplace))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(PatientAgent other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    PatientAgent typedOther = (PatientAgent)other;

    lastComparison = Boolean.valueOf(isSetNpasp()).compareTo(typedOther.isSetNpasp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNpasp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.npasp, typedOther.npasp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFam()).compareTo(typedOther.isSetFam());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFam()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fam, typedOther.fam);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIm()).compareTo(typedOther.isSetIm());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIm()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.im, typedOther.im);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOt()).compareTo(typedOther.isSetOt());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOt()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ot, typedOther.ot);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDatar()).compareTo(typedOther.isSetDatar());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDatar()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.datar, typedOther.datar);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPol()).compareTo(typedOther.isSetPol());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPol()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pol, typedOther.pol);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetName_str()).compareTo(typedOther.isSetName_str());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName_str()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name_str, typedOther.name_str);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOgrn_str()).compareTo(typedOther.isSetOgrn_str());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOgrn_str()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ogrn_str, typedOther.ogrn_str);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetVpolis()).compareTo(typedOther.isSetVpolis());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVpolis()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.vpolis, typedOther.vpolis);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSpolis()).compareTo(typedOther.isSetSpolis());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSpolis()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.spolis, typedOther.spolis);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNpolis()).compareTo(typedOther.isSetNpolis());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNpolis()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.npolis, typedOther.npolis);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTdoc()).compareTo(typedOther.isSetTdoc());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTdoc()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tdoc, typedOther.tdoc);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDocser()).compareTo(typedOther.isSetDocser());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDocser()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.docser, typedOther.docser);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDocnum()).compareTo(typedOther.isSetDocnum());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDocnum()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.docnum, typedOther.docnum);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBirthplace()).compareTo(typedOther.isSetBirthplace());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBirthplace()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.birthplace, typedOther.birthplace);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PatientAgent(");
    boolean first = true;

    sb.append("npasp:");
    sb.append(this.npasp);
    first = false;
    if (!first) sb.append(", ");
    sb.append("fam:");
    if (this.fam == null) {
      sb.append("null");
    } else {
      sb.append(this.fam);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("im:");
    if (this.im == null) {
      sb.append("null");
    } else {
      sb.append(this.im);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ot:");
    if (this.ot == null) {
      sb.append("null");
    } else {
      sb.append(this.ot);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("datar:");
    sb.append(this.datar);
    first = false;
    if (!first) sb.append(", ");
    sb.append("pol:");
    sb.append(this.pol);
    first = false;
    if (!first) sb.append(", ");
    sb.append("name_str:");
    if (this.name_str == null) {
      sb.append("null");
    } else {
      sb.append(this.name_str);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ogrn_str:");
    if (this.ogrn_str == null) {
      sb.append("null");
    } else {
      sb.append(this.ogrn_str);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("vpolis:");
    sb.append(this.vpolis);
    first = false;
    if (!first) sb.append(", ");
    sb.append("spolis:");
    if (this.spolis == null) {
      sb.append("null");
    } else {
      sb.append(this.spolis);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("npolis:");
    if (this.npolis == null) {
      sb.append("null");
    } else {
      sb.append(this.npolis);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("tdoc:");
    sb.append(this.tdoc);
    first = false;
    if (!first) sb.append(", ");
    sb.append("docser:");
    if (this.docser == null) {
      sb.append("null");
    } else {
      sb.append(this.docser);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("docnum:");
    if (this.docnum == null) {
      sb.append("null");
    } else {
      sb.append(this.docnum);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("birthplace:");
    if (this.birthplace == null) {
      sb.append("null");
    } else {
      sb.append(this.birthplace);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PatientAgentStandardSchemeFactory implements SchemeFactory {
    public PatientAgentStandardScheme getScheme() {
      return new PatientAgentStandardScheme();
    }
  }

  private static class PatientAgentStandardScheme extends StandardScheme<PatientAgent> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PatientAgent struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NPASP
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.npasp = iprot.readI32();
              struct.setNpaspIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FAM
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.fam = iprot.readString();
              struct.setFamIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // IM
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.im = iprot.readString();
              struct.setImIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // OT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ot = iprot.readString();
              struct.setOtIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // DATAR
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.datar = iprot.readI64();
              struct.setDatarIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // POL
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.pol = iprot.readI32();
              struct.setPolIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // NAME_STR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name_str = iprot.readString();
              struct.setName_strIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // OGRN_STR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ogrn_str = iprot.readString();
              struct.setOgrn_strIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // VPOLIS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.vpolis = iprot.readI32();
              struct.setVpolisIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // SPOLIS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.spolis = iprot.readString();
              struct.setSpolisIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // NPOLIS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.npolis = iprot.readString();
              struct.setNpolisIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // TDOC
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.tdoc = iprot.readI32();
              struct.setTdocIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // DOCSER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.docser = iprot.readString();
              struct.setDocserIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 14: // DOCNUM
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.docnum = iprot.readString();
              struct.setDocnumIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 15: // BIRTHPLACE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.birthplace = iprot.readString();
              struct.setBirthplaceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PatientAgent struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(NPASP_FIELD_DESC);
      oprot.writeI32(struct.npasp);
      oprot.writeFieldEnd();
      if (struct.fam != null) {
        oprot.writeFieldBegin(FAM_FIELD_DESC);
        oprot.writeString(struct.fam);
        oprot.writeFieldEnd();
      }
      if (struct.im != null) {
        oprot.writeFieldBegin(IM_FIELD_DESC);
        oprot.writeString(struct.im);
        oprot.writeFieldEnd();
      }
      if (struct.ot != null) {
        oprot.writeFieldBegin(OT_FIELD_DESC);
        oprot.writeString(struct.ot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(DATAR_FIELD_DESC);
      oprot.writeI64(struct.datar);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(POL_FIELD_DESC);
      oprot.writeI32(struct.pol);
      oprot.writeFieldEnd();
      if (struct.name_str != null) {
        oprot.writeFieldBegin(NAME_STR_FIELD_DESC);
        oprot.writeString(struct.name_str);
        oprot.writeFieldEnd();
      }
      if (struct.ogrn_str != null) {
        oprot.writeFieldBegin(OGRN_STR_FIELD_DESC);
        oprot.writeString(struct.ogrn_str);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(VPOLIS_FIELD_DESC);
      oprot.writeI32(struct.vpolis);
      oprot.writeFieldEnd();
      if (struct.spolis != null) {
        oprot.writeFieldBegin(SPOLIS_FIELD_DESC);
        oprot.writeString(struct.spolis);
        oprot.writeFieldEnd();
      }
      if (struct.npolis != null) {
        oprot.writeFieldBegin(NPOLIS_FIELD_DESC);
        oprot.writeString(struct.npolis);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TDOC_FIELD_DESC);
      oprot.writeI32(struct.tdoc);
      oprot.writeFieldEnd();
      if (struct.docser != null) {
        oprot.writeFieldBegin(DOCSER_FIELD_DESC);
        oprot.writeString(struct.docser);
        oprot.writeFieldEnd();
      }
      if (struct.docnum != null) {
        oprot.writeFieldBegin(DOCNUM_FIELD_DESC);
        oprot.writeString(struct.docnum);
        oprot.writeFieldEnd();
      }
      if (struct.birthplace != null) {
        oprot.writeFieldBegin(BIRTHPLACE_FIELD_DESC);
        oprot.writeString(struct.birthplace);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PatientAgentTupleSchemeFactory implements SchemeFactory {
    public PatientAgentTupleScheme getScheme() {
      return new PatientAgentTupleScheme();
    }
  }

  private static class PatientAgentTupleScheme extends TupleScheme<PatientAgent> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PatientAgent struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetNpasp()) {
        optionals.set(0);
      }
      if (struct.isSetFam()) {
        optionals.set(1);
      }
      if (struct.isSetIm()) {
        optionals.set(2);
      }
      if (struct.isSetOt()) {
        optionals.set(3);
      }
      if (struct.isSetDatar()) {
        optionals.set(4);
      }
      if (struct.isSetPol()) {
        optionals.set(5);
      }
      if (struct.isSetName_str()) {
        optionals.set(6);
      }
      if (struct.isSetOgrn_str()) {
        optionals.set(7);
      }
      if (struct.isSetVpolis()) {
        optionals.set(8);
      }
      if (struct.isSetSpolis()) {
        optionals.set(9);
      }
      if (struct.isSetNpolis()) {
        optionals.set(10);
      }
      if (struct.isSetTdoc()) {
        optionals.set(11);
      }
      if (struct.isSetDocser()) {
        optionals.set(12);
      }
      if (struct.isSetDocnum()) {
        optionals.set(13);
      }
      if (struct.isSetBirthplace()) {
        optionals.set(14);
      }
      oprot.writeBitSet(optionals, 15);
      if (struct.isSetNpasp()) {
        oprot.writeI32(struct.npasp);
      }
      if (struct.isSetFam()) {
        oprot.writeString(struct.fam);
      }
      if (struct.isSetIm()) {
        oprot.writeString(struct.im);
      }
      if (struct.isSetOt()) {
        oprot.writeString(struct.ot);
      }
      if (struct.isSetDatar()) {
        oprot.writeI64(struct.datar);
      }
      if (struct.isSetPol()) {
        oprot.writeI32(struct.pol);
      }
      if (struct.isSetName_str()) {
        oprot.writeString(struct.name_str);
      }
      if (struct.isSetOgrn_str()) {
        oprot.writeString(struct.ogrn_str);
      }
      if (struct.isSetVpolis()) {
        oprot.writeI32(struct.vpolis);
      }
      if (struct.isSetSpolis()) {
        oprot.writeString(struct.spolis);
      }
      if (struct.isSetNpolis()) {
        oprot.writeString(struct.npolis);
      }
      if (struct.isSetTdoc()) {
        oprot.writeI32(struct.tdoc);
      }
      if (struct.isSetDocser()) {
        oprot.writeString(struct.docser);
      }
      if (struct.isSetDocnum()) {
        oprot.writeString(struct.docnum);
      }
      if (struct.isSetBirthplace()) {
        oprot.writeString(struct.birthplace);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PatientAgent struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(15);
      if (incoming.get(0)) {
        struct.npasp = iprot.readI32();
        struct.setNpaspIsSet(true);
      }
      if (incoming.get(1)) {
        struct.fam = iprot.readString();
        struct.setFamIsSet(true);
      }
      if (incoming.get(2)) {
        struct.im = iprot.readString();
        struct.setImIsSet(true);
      }
      if (incoming.get(3)) {
        struct.ot = iprot.readString();
        struct.setOtIsSet(true);
      }
      if (incoming.get(4)) {
        struct.datar = iprot.readI64();
        struct.setDatarIsSet(true);
      }
      if (incoming.get(5)) {
        struct.pol = iprot.readI32();
        struct.setPolIsSet(true);
      }
      if (incoming.get(6)) {
        struct.name_str = iprot.readString();
        struct.setName_strIsSet(true);
      }
      if (incoming.get(7)) {
        struct.ogrn_str = iprot.readString();
        struct.setOgrn_strIsSet(true);
      }
      if (incoming.get(8)) {
        struct.vpolis = iprot.readI32();
        struct.setVpolisIsSet(true);
      }
      if (incoming.get(9)) {
        struct.spolis = iprot.readString();
        struct.setSpolisIsSet(true);
      }
      if (incoming.get(10)) {
        struct.npolis = iprot.readString();
        struct.setNpolisIsSet(true);
      }
      if (incoming.get(11)) {
        struct.tdoc = iprot.readI32();
        struct.setTdocIsSet(true);
      }
      if (incoming.get(12)) {
        struct.docser = iprot.readString();
        struct.setDocserIsSet(true);
      }
      if (incoming.get(13)) {
        struct.docnum = iprot.readString();
        struct.setDocnumIsSet(true);
      }
      if (incoming.get(14)) {
        struct.birthplace = iprot.readString();
        struct.setBirthplaceIsSet(true);
      }
    }
  }

}

