/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ru.nkz.ivcgzo.thriftCommon.classifier;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum IntegerClassifiers implements org.apache.thrift.TEnum {
  n_aba(1),
  n_abb(2),
  n_abc(3),
  n_abd(4),
  n_abg(5),
  n_abs(6),
  n_abt(7),
  n_abv(8),
  n_abx(9),
  n_aby(10),
  n_af0(11),
  n_ai0(12),
  n_al0(13),
  n_alk(14),
  n_am0(15),
  n_ao0(16),
  n_ap0(17),
  n_aq0(18),
  n_arez(19),
  n_az0(20),
  n_az9(21),
  n_azt(22),
  n_d0s(23),
  n_db1(24),
  n_db2(25),
  n_db3(26),
  n_db4(27),
  n_db5(28),
  n_db7(30),
  n_db8(31),
  n_edd(32),
  n_f008(33),
  n_frm(34),
  n_frw(35),
  n_grup(36),
  n_kas(37),
  n_l00(38),
  n_l01(39),
  n_l02(40),
  n_lds(41),
  n_lkn(42),
  n_lkr(43),
  n_m00(44),
  n_med(45),
  n_mnn(46),
  n_n00(47),
  n_o00(48),
  n_opl(49),
  n_p07(50),
  n_p0e1(51),
  n_p0s(52),
  n_priznd(53),
  n_r0l(54),
  n_rzd(55),
  n_t00(56),
  n_u00(57),
  n_u10(58),
  n_u50(59),
  n_vdi(60),
  n_vgo(61),
  n_vp2(62),
  n_vp3(63),
  n_vtr(64),
  n_w04(65),
  n_w07(66),
  n_z00(67),
  n_z01(68),
  n_z10(69),
  n_z30(70),
  n_z42(71),
  n_z43(72),
  n_z60(73),
  n_z70(74),
  n_z80(75),
  n_z90(76),
  n_z11(77),
  n_spec(78),
  n_din(79),
  n_p0c(80),
  n_v10(81),
  n_v0a(82),
  n_v0b(83),
  n_v0c(84),
  n_v0d(85),
  n_v0e(86),
  n_v0f(87),
  n_v0g(88),
  n_v0h(89),
  n_v0m(90),
  n_v0n(91),
  n_v0p(92),
  n_v0r(93),
  n_v0s(94),
  n_v0t(95);

  private final int value;

  private IntegerClassifiers(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static IntegerClassifiers findByValue(int value) { 
    switch (value) {
      case 1:
        return n_aba;
      case 2:
        return n_abb;
      case 3:
        return n_abc;
      case 4:
        return n_abd;
      case 5:
        return n_abg;
      case 6:
        return n_abs;
      case 7:
        return n_abt;
      case 8:
        return n_abv;
      case 9:
        return n_abx;
      case 10:
        return n_aby;
      case 11:
        return n_af0;
      case 12:
        return n_ai0;
      case 13:
        return n_al0;
      case 14:
        return n_alk;
      case 15:
        return n_am0;
      case 16:
        return n_ao0;
      case 17:
        return n_ap0;
      case 18:
        return n_aq0;
      case 19:
        return n_arez;
      case 20:
        return n_az0;
      case 21:
        return n_az9;
      case 22:
        return n_azt;
      case 23:
        return n_d0s;
      case 24:
        return n_db1;
      case 25:
        return n_db2;
      case 26:
        return n_db3;
      case 27:
        return n_db4;
      case 28:
        return n_db5;
      case 30:
        return n_db7;
      case 31:
        return n_db8;
      case 32:
        return n_edd;
      case 33:
        return n_f008;
      case 34:
        return n_frm;
      case 35:
        return n_frw;
      case 36:
        return n_grup;
      case 37:
        return n_kas;
      case 38:
        return n_l00;
      case 39:
        return n_l01;
      case 40:
        return n_l02;
      case 41:
        return n_lds;
      case 42:
        return n_lkn;
      case 43:
        return n_lkr;
      case 44:
        return n_m00;
      case 45:
        return n_med;
      case 46:
        return n_mnn;
      case 47:
        return n_n00;
      case 48:
        return n_o00;
      case 49:
        return n_opl;
      case 50:
        return n_p07;
      case 51:
        return n_p0e1;
      case 52:
        return n_p0s;
      case 53:
        return n_priznd;
      case 54:
        return n_r0l;
      case 55:
        return n_rzd;
      case 56:
        return n_t00;
      case 57:
        return n_u00;
      case 58:
        return n_u10;
      case 59:
        return n_u50;
      case 60:
        return n_vdi;
      case 61:
        return n_vgo;
      case 62:
        return n_vp2;
      case 63:
        return n_vp3;
      case 64:
        return n_vtr;
      case 65:
        return n_w04;
      case 66:
        return n_w07;
      case 67:
        return n_z00;
      case 68:
        return n_z01;
      case 69:
        return n_z10;
      case 70:
        return n_z30;
      case 71:
        return n_z42;
      case 72:
        return n_z43;
      case 73:
        return n_z60;
      case 74:
        return n_z70;
      case 75:
        return n_z80;
      case 76:
        return n_z90;
      case 77:
        return n_z11;
      case 78:
        return n_spec;
      case 79:
        return n_din;
      case 80:
        return n_p0c;
      case 81:
        return n_v10;
      case 82:
        return n_v0a;
      case 83:
        return n_v0b;
      case 84:
        return n_v0c;
      case 85:
        return n_v0d;
      case 86:
        return n_v0e;
      case 87:
        return n_v0f;
      case 88:
        return n_v0g;
      case 89:
        return n_v0h;
      case 90:
        return n_v0m;
      case 91:
        return n_v0n;
      case 92:
        return n_v0p;
      case 93:
        return n_v0r;
      case 94:
        return n_v0s;
      case 95:
        return n_v0t;
      default:
        return null;
    }
  }
}
